### ISSUE TITLE
amend the data generator to include contacts

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-palisade#7]
We are looking to randomly generate contact phone numbers for personal and work numbers

**Comment by planetf1** [comment]
Would be neat if generating fake phone numbers to keep them non-genuine. ie see https://www.numbersupermarket.co.uk/fake-number-ranges-here-are-the-numbers-reserved-exclusively-for-tv-radio-shows/ for reserved numbers - though that is uk specific. other countries may vary

**Comment by davidradl** [comment]
@planetf1 I have just used the existing Palisade PhoneNumber.generate method to generate the phone numbers. I suggest that this could be an idea to enhance the Palisade generator. I suggest raising an issue against Palisade, if you think we need this.
